### ISSUE TITLE
Make path of binary configureable

### ISSUE THREAD

**Issue by h4cc** [h2non/grunt-beautiful-docs#2]
Is it possible to make the path of the used binary configureable?

`bfdocsBin = "#{__dirname}/../node_modules/beautiful-docs/bin/bfdocs"`

**Comment by h2non** [comment]
Feature supported in `0.1.1`.

Task option: `bfdocsBinary: "path/to/binary"`

Update your dependency tree:

```
npm update grunt-beautiful-docs
```

**Comment by h2non** [comment]
Docs: https://github.com/h2non/grunt-beautiful-docs#bfdocsbinary

**Comment by h4cc** [comment]
:+1: Thanks!
